Sprint 6 - final task.
imposmas/java-kanban pull request #1
Opened 2024-12-01 19:43 UTC by imposmas

2024-12-02 20:11 UTC, Fleaman777 requested changes

2024-12-02 20:11 UTC, Fleaman777 commented on src/ru/yandex/practicum/kanban/managers/InMemoryHistoryManager.java
> +    HashMap<Integer, Node> tasksHistory = new HashMap<>();
Лучше сделать поля private, чтобы обеспечить инкапсуляцию.

2024-12-02 20:11 UTC, Fleaman777 commented on src/ru/yandex/practicum/kanban/managers/InMemoryHistoryManager.java
> +    }
Пропущена обработка связей в случае если after == null. Добавь after.prev = before в первый блок и before.next = after во второй.

2024-12-02 20:11 UTC, Fleaman777 commented on src/ru/yandex/practicum/kanban/managers/InMemoryHistoryManager.java
> +    private static class Node {
отличное решение, сделать этот класс внутренним

2024-12-02 20:11 UTC, Fleaman777 commented on test/ru/yandex/practicum/kanban/managers/InMemoryHistoryManagerTest.java
> +    void HistoryDoesNotStoreDuplicatesTest() {
по джава код стайлу: методы должны начинаться с маленькой буквы

2024-12-02 20:11 UTC, Fleaman777 commented on test/ru/yandex/practicum/kanban/managers/InMemoryTaskManagerTest.java
> +        assertTrue(!taskManager.getEpicSubTasks(epicId1).contains(SubTaskId2));
вижу. что новые тесты добавлены, это хорошо. 
но посмотри еще раз задание, какие кейсы необходимо покрыть

2024-12-03 20:02 UTC, imposmas commented
если с тестами все еще в пролете, то подскажи пожалуйста как будет правильно реализовать их 
дохожу до того, что не могу создать ломаные объекты чтоб потом на них какое либо действие проверить, потому что везде куча проверок на соотвесвие....

2024-12-05 06:56 UTC, VadimZharkov commented on src/ru/yandex/practicum/kanban/managers/InMemoryTaskManager.java
HistoryManager historyManager - модификатор доступа?

2024-12-05 06:58 UTC, VadimZharkov commented on src/ru/yandex/practicum/kanban/managers/InMemoryHistoryManager.java
> +        if (tasksHistory.get(id) != null) {
Лучше за одно обращение к мапе
```
Node node = tasksHistory.get(task.getId());
if (node != null) {
      removeNode(node);
}
```

2024-12-05 07:00 UTC, VadimZharkov requested changes
Можно улучшить

2024-12-05 17:24 UTC, VadimZharkov approved these changes

2025-05-24 16:15 UTC, merged